### ISSUE TITLE
Siemka problem z uruchomieniem

### ISSUE THREAD

**Issue by MakaiuPL** [janek515/spotted#1]
SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if flask.request.args is None or len(flask.request.args) is not 1:
Traceback (most recent call last):
  File "C:\Users\Max\Downloads\spotted-master(1)\spotted-master\wsgi.py", line 3, in <module>
    from api.api import app
  File "C:\Users\Max\Downloads\spotted-master(1)\spotted-master\api\api.py", line 2, in <module>
    from builtins import function
ImportError: cannot import name 'function' from 'builtins' (unknown location)

mam takie cos nie wazne czy windows czy linux, python3.10

**Comment by janek515** [comment]
Siemka, repo stare, nie maintainowane, zaraz postaram sie zrobic repro

**Comment by janek515** [comment]
Powinno działać daj znać jeśli coś będzie nie tak
